services:
  openvpn:
    build: .
    container_name: degonet-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      degonet-network:
        ipv4_address: 10.10.0.2
    volumes:
      - openvpn_data:/etc/openvpn/ccds
      - openvpn_db:/etc/openvpn/data
    environment:
      DB_FILE: /etc/openvpn/data/users.sqlite
      CCD_DIR: /etc/openvpn/ccds
      DEFAULT_NETMASK: 255.255.255.0

volumes:
  openvpn_data:
  openvpn_db:

networks:
  degonet-network:
    external: true
