services:
  openvpn:
    build: .
    container_name: degonet-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ./
        target: /etc/openvpn
